name: linux-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: without lib
      run: ./build/01-helloworld/HelloWorld
    - name: with static linking
      run: ./build/02-helloworldlib/helloworld_static
    - name: with dynamic linking
      run: ./build/02-helloworldlib/helloworld_shared
