name: linux-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: SDL3_install
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/libsdl-org/SDL.git
        mkdir SDL/build
        cmake -S SDL -B SDL/build -DSDL_STATIC=ON
        cmake --build SDL/build
        sudo cmake --install SDL/build
        
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
